- name: Setup back-end as service
  become: true
  template:
    src: ../templates/gateway-server.service.j2
    dest: /etc/systemd/system/gateway-server.service

- name: Setup celery workers as service
  become: true
  template:
    src: ../templates/gateway-workers.service.j2
    dest: /etc/systemd/system/gateway-workers.service

- name: Setup celery helpers as service
  become: true
  template:
    src: ../templates/gateway-registration-helpers.service.j2
    dest: /etc/systemd/system/gateway-registration-helpers.service

- name: Setup celery tools as service
  become: true
  template:
    src: ../templates/gateway-scheduled-tools.service.j2
    dest: /etc/systemd/system/gateway-scheduled-tools.service

- name: Setup celery beat as service
  become: true
  template:
    src: ../templates/gateway-beat.service.j2
    dest: /etc/systemd/system/gateway-beat.service
