- name: Install required packages
  become: true
  package:
    update_cache: yes
    name: [gunicorn]
    state: present

- name: Ensure git is installed
  apt:
    name: git
    state: present
- name: Clone repository
  git:
    repo: 'https://github.com/pastelnetwork/gateway-api.git'
    dest: '~/gateway/'

- name: Install poetry
  ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
- name: Add poetry to PATH
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: PATH="$HOME/.local/bin:$PATH"
    create: yes

- name: Set PYTHONPATH
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: export PYTHONPATH=$PYTHONPATH:/home/ubuntu/gateway/backend/app
    create: yes

- name: Read pastel.conf from remote host
  ansible.builtin.slurp:
    src: ~/.pastel/pastel.conf
  register: pastel_conf

- name: decode remote content
  set_fact:
    remote_content: "{{pastel_conf.content | b64decode}}"

- name: find rpcport
  set_fact:
    rpcport: "{{ remote_content | regex_search('(rpcport=)(.*)', '\\2') | first }}"
- name: find rpcuser
  set_fact:
    rpcuser: "{{ remote_content | regex_search('(rpcuser=)(.*)', '\\2') | first }}"
- name: find rpcpassword
  set_fact:
    rpcpassword: "{{ remote_content | regex_search('(rpcpassword=)(.*)', '\\2') | first }}"

- name: Copy back end .env
  template:
    src: ../templates/dot-env.j2
    dest: ~/gateway/.env

- name: Setup back-end as service
  become: true
  template:
    src: ../templates/gateway-server.service.j2
    dest: /etc/systemd/system/gateway-server.service

- name: Setup celery workers as service
  become: true
  template:
    src: ../templates/gateway-workers.service.j2
    dest: /etc/systemd/system/gateway-workers.service

- name: Setup celery helpers as service
  become: true
  template:
    src: ../templates/gateway-registration-helpers.service.j2
    dest: /etc/systemd/system/gateway-registration-helpers.service

- name: Setup celery tools as service
  become: true
  template:
    src: ../templates/gateway-scheduled-tools.service.j2
    dest: /etc/systemd/system/gateway-scheduled-tools.service

- name: Setup celery beat as service
  become: true
  template:
    src: ../templates/gateway-beat.service.j2
    dest: /etc/systemd/system/gateway-beat.service

- name: Setup celery account manager as service
  become: true
  template:
    src: ../templates/gateway-account-manager.service.j2
    dest: /etc/systemd/system/gateway-account-manager.service
