- name: Download ipfs
  ansible.builtin.get_url:
    # url: 'https://dist.ipfs.tech/kubo/v0.14.0/kubo_v0.14.0_linux-amd64.tar.gz'
    # dest: ~/kubo_v0.14.0_linux-amd64.tar.gz
    url: 'https://github.com/ipfs/kubo/releases/download/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz'
    dest: ~/go-ipfs_v0.7.0_linux-amd64.tar.gz

- name: Unarchive
  ansible.builtin.unarchive:
    src: ~/go-ipfs_v0.7.0_linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Install ipfs
  become: true
  ansible.builtin.shell:
    cmd: bash install.sh
    # chdir: /tmp/kubo
    chdir: /tmp/go-ipfs

- name: Init ipfs
  ansible.builtin.shell: ipfs init

- name: Copy ipfs.service
  become: true
  template:
    src: ../templates/ipfs.service.j2
    dest: /etc/systemd/system/ipfs.service

- name: Start ipfs.service
  become: true
  systemd: 
    state: started
    name: ipfs
    daemon_reload: yes
