- name: install nfs-common
  become: true
  apt:
    name: nfs-common
    state: present
- name: create mount point
  become: true
  file:
    path: /mnt/efs
    state: directory
- name: mount efs
  become: true
  mount:
    src: "{{ hostvars['localhost']['mount_target'] }}:/"
    path: /mnt/efs
    fstype: nfs
    opts: defaults
- name: add to fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    line: "{{ hostvars['localhost']['mount_target'] }}:/ /mnt/efs nfs defaults 0 0"
- name: Change ownership of directory
  become: true
  file:
    path: /mnt/efs
    owner: ubuntu
    group: ubuntu
    state: directory
- name: create image share directory
  file:
    path: /mnt/efs/images
    state: directory
    mode: "u+rwx,g+rwx,o+rx"
- name: create pastelid share directory
  file:
    path: /mnt/efs/pastelids
    state: directory
    mode: "u+rwx,g+rwx,o+rx"
- name: Create symbolic link to pastelid directory
  file:
    src: /mnt/efs/pastelids
    dest: '{{pastel_data_path}}/pastelkeys'
    state: link