- name: install nfs-common
  apt:
    name: nfs-common
    state: present
- name: create mount point
  file:
    path: /mnt/efs
    state: directory
- name: mount efs
  mount:
    src: "{{ hostvars['localhost']['mount_target'] }}:/"
    path: /mnt/efs
    fstype: nfs
    opts: defaults
- name: add to fstab
  lineinfile:
    dest: /etc/fstab
    line: "{{ hostvars['localhost']['mount_target'] }}:/ /mnt/efs nfs defaults 0 0"
