galaxy_info:
  author: Torsten Juergeleit
  description: Install zsh and oh-my-zsh

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: GenericLinux
      versions:
      - all
  
  galaxy_tags:
    - system

dependencies: []
