---

- name: Basic host setup
  hosts: all
  tasks:
  - name: Install required packages
    become: true
    package:
      update_cache: yes
      name: [git, curl, wget, zip, unzip, vim, libgomp1, build-essential, libsodium-dev]
      state: present
  roles:
    - { role: ansible-role-zsh, zsh_ohmy_theme: robbyrussell, zsh_ohmy_plugins: [git, git-extras, zsh-autosuggestions zsh-syntax-highlighting] }
  tags: common_host_setup

Proxy/Front-end host setup
- hosts: proxy
  tasks:
    - name: Setup nginx
      ansible.builtin.include_tasks: ./includes/install-nginx.yaml

    - name: Instal docker
      ansible.builtin.include_tasks: ./includes/install-docker.yaml

    - name: Instal flowers and pgadmin as docker containers
      ansible.builtin.include_tasks: ./includes/setup-tools.yaml

    # - name: Instal frontend
    #   ansible.builtin.include_tasks: ./includes/install-frontend.yaml
  tags: proxy_host_setup

- name: Master host setup
  hosts: master
  tasks:
    - name: Instal redis
      ansible.builtin.include_tasks: ./includes/install-redis.yaml

    - name: Instal IPFS
      ansible.builtin.include_tasks: ./includes/install-ipfs.yaml

    - name: Instal walletnode
      ansible.builtin.include_tasks: ./includes/install-walletnode.yaml

    - name: Instal API back-end
      ansible.builtin.include_tasks: ./includes/install-backend.yaml
      vars:
        redis_host: localhost

    - name: Setup EFS mount
      ansible.builtin.include_tasks: ./includes/setup-efs-mount.yaml
  tags: master_host_setup

- name: Worker host setup
  hosts: workers
  tasks:
    - name: Instal IPFS
      ansible.builtin.include_tasks: ./includes/install-ipfs.yaml

    - name: Instal walletnode
      ansible.builtin.include_tasks: ./includes/install-walletnode.yaml

    - name: Instal API back-end
      ansible.builtin.include_tasks: ./includes/install-backend.yaml
      vars:
        redis_host: '{{ redis_internal_host }}'

    - name: Setup EFS mount
      ansible.builtin.include_tasks: ./includes/setup-efs-mount.yaml
  tags: worker_host_setup

...